CREATE TABLE users (
                       id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       first_name  VARCHAR(255) NOT NULL,
                       last_name   VARCHAR(255) NOT NULL,
                       email       VARCHAR(255) NOT NULL UNIQUE,
                       password    VARCHAR(255) NOT NULL,
                       phone       VARCHAR(255),
                       dob         DATE,
                       role        VARCHAR(20)  NOT NULL CHECK (role IN ('CUSTOMER', 'ADMIN')),
                       created_at  TIMESTAMP    NOT NULL DEFAULT now()
);

CREATE TABLE categories (
                            id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            name        VARCHAR(255) NOT NULL,
                            description TEXT
);

CREATE TABLE products (
                          id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          category_id    BIGINT REFERENCES categories(id),
                          name           VARCHAR(255)   NOT NULL,
                          description    TEXT,
                          sku            VARCHAR(100),
                          brand          VARCHAR(255),
                          price          NUMERIC(10, 2) CHECK (price IS NULL OR price >= 0),
                          stock_quantity INTEGER        CHECK (stock_quantity IS NULL OR stock_quantity >= 0),
                          active         BOOLEAN        NOT NULL DEFAULT true,
                          created_at     TIMESTAMP      NOT NULL DEFAULT now()
);

CREATE TABLE product_variants (
                                  id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                  product_id     BIGINT REFERENCES products(id) ON DELETE CASCADE,
                                  size           VARCHAR(50),
                                  color          VARCHAR(50),
                                  price          NUMERIC(10, 2) NOT NULL CHECK (price >= 0),
                                  stock_quantity INTEGER        NOT NULL DEFAULT 0 CHECK (stock_quantity >= 0)
);

CREATE TABLE carts (
                       id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       user_id    BIGINT UNIQUE REFERENCES users(id),
                       created_at TIMESTAMP NOT NULL DEFAULT now()
);

CREATE TABLE cart_items (
                            id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            cart_id             BIGINT  REFERENCES carts(id) ON DELETE CASCADE,
                            product_variant_id  BIGINT  REFERENCES product_variants(id),
                            quantity            INTEGER NOT NULL CHECK (quantity > 0),
                            UNIQUE (cart_id, product_variant_id)
);

CREATE TABLE addresses (
                           id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           user_id     BIGINT REFERENCES users(id),
                           street      VARCHAR(255),
                           city        VARCHAR(255),
                           province    VARCHAR(255),
                           postal_code VARCHAR(20),
                           country     VARCHAR(255)
);

CREATE TABLE orders (
                        id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        user_id      BIGINT REFERENCES users(id),
                        address_id   BIGINT REFERENCES addresses(id),
                        order_status VARCHAR(20)    NOT NULL
                            CHECK (order_status IN ('PENDING', 'CONFIRMED', 'PROCESSING', 'SHIPPED', 'DELIVERED', 'CANCELLED')),
                        total        NUMERIC(10, 2) NOT NULL DEFAULT 0 CHECK (total >= 0),
                        created_at   TIMESTAMP      NOT NULL DEFAULT now()
);

CREATE TABLE order_items (
                             id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             order_id            BIGINT REFERENCES orders(id) ON DELETE CASCADE,
                             product_variant_id  BIGINT REFERENCES product_variants(id),
                             quantity            INTEGER        NOT NULL CHECK (quantity > 0),
                             price               NUMERIC(10, 2) NOT NULL CHECK (price >= 0)
);

CREATE TABLE payments (
                          id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          order_id       BIGINT UNIQUE REFERENCES orders(id),
                          payment_status VARCHAR(20)    NOT NULL
                              CHECK (payment_status IN ('PENDING', 'PAID', 'FAILED', 'REFUNDED')),
                          payment_method VARCHAR(20)
                              CHECK (payment_method IS NULL OR payment_method IN ('CARD', 'EFT', 'CASH_ON_DELIVERY')),
                          amount         NUMERIC(10, 2) NOT NULL CHECK (amount >= 0),
                          transaction_id VARCHAR(255),
                          paid_at        TIMESTAMP
);

CREATE INDEX idx_products_category_id ON products(category_id);
CREATE INDEX idx_product_variants_product_id ON product_variants(product_id);
CREATE INDEX idx_cart_items_cart_id ON cart_items(cart_id);
CREATE INDEX idx_addresses_user_id ON addresses(user_id);
CREATE INDEX idx_orders_user_id ON orders(user_id);
CREATE INDEX idx_orders_order_status ON orders(order_status);
CREATE INDEX idx_order_items_order_id ON order_items(order_id);
CREATE INDEX idx_payments_payment_status ON payments(payment_status);